dependencies:
- name: bdd-gh-1578669405
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1578669405
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-import-1578671354
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1578669405
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1578668737
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
